### ISSUE TITLE
User does not have read access to usr/local/bin/ansible-playbook

### ISSUE THREAD

**Issue by jamesdowdall** [UKHomeOffice/development_environment#103]
## Expected Behavior
User should be able to run ansible playbooks as a non-privileged user.

## Current Behavior
User does not have read access to usr/local/bin/ansible-playbook directory, so they cannot run ansible-playbooks.
User does have execute access to this directory.

This problem extends to all ansible commands on the system

## Possible Solution
(run privileged) chmod 755 usr/local/bin/ansible-playbook 

## Context
Trying to run ansible-playbooks as a user

## Your Environment
* Version used: v1.1.3
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by pixie79** [comment]
Users do not have permission to run Ansible-playbook as this requires root access. If you are looking at it for local use the you should be using a copy in a local python env within the users home. This does not then interfer with the system

**Comment by pi-unnerup** [comment]
Just to confirm, it is not currently installed in a local space for the user?
We propose to include the install script in developer_user_environment.

**Comment by pixie79** [comment]
correct - if it is needed to users, then it should be installed as part of the users local python virtual environment. venv. The same as the awscli tools. This could be added by a simple bash install script to the developer_user_environment.
