### ISSUE TITLE
Wifi requires rebooting

### ISSUE THREAD

**Issue by pi-unnerup** [UKHomeOffice/development_environment#104]
After Standby, no WiFi networks can be found on new Laptops

## Expected Behavior
WiFi should be available as normal, even after Standby

## Current Behavior
No WiFi networks appear after Standby and no connection is possible. Requires a reboot for functioning WiFi. It happens on several computers, but not consistently every time.

## Steps to Reproduce (for bugs)
1. Laptop goes in Standby
2. User awakens Laptop and logs in
3. User attempts to connect to WiFi

## Context

Occasionally TrashCan Network can be seen. Restarting Network Manager Service fixes it also.

## Your Environment

* Version used: v.1.1.3 imaging of DELL XPS13
* Browser Name and version: Ubuntu

**Comment by pixie79** [comment]
I have not noticed this did you lock the device before going into standby

**Comment by pi-unnerup** [comment]
Hi Mark,
I am not entirely sure of my behaviour before the times it has happened, although I have definitely not locked it on all the occasions (which is around 3/4 so far). It has happened to Sam Irvine as well and he is also not sure what he has done to prompt it.

**Comment by Ian-T-Price** [comment]
This happens regularly on my build (approx 3 months old; version???).

Definitely happens when the screen is shut, whether the device is locked or not.

**Comment by pixie79** [comment]
hm, i have not seen it on mine. but i do make a point of locking the screen each time as we are required under the SyOps to do.

It may also depend on the display manager used.

**Comment by fosuoy** [comment]
We can use visudo to allow the staff group to restart networking as root and only do that - that would be appropriate here no?

**Comment by pixie79** [comment]
No

We fix the problem Ianand Pi have the solution restarting networking or giving out root is not

**Comment by sirv1ne** [comment]
Appears to be fixed in latest merge.
