### ISSUE TITLE
Kubectl needs updating to version 1.4.7

### ISSUE THREAD

**Issue by pi-unnerup** [UKHomeOffice/development_environment#105]
Kubectl is 1.3.4 and should be 1.4.7

## Expected Behavior
Kubectl should be 1.4.7

## Current Behavior
Kubectl is 1.3.4

## Steps to Reproduce (for bugs)
run "kubectl version"

## Your Environment
Version 1.1.3

**Comment by jamesdowdall** [comment]
Kube v1.5.3 or higher (latest) is preferred
