### ISSUE TITLE
Disk space issues caused by odd partitioning

### ISSUE THREAD

**Issue by SamFrier** [UKHomeOffice/development_environment#27]
Disk space on the laptops is quickly running out during normal usage due to the root partition only being 9.3GB in size. This will only become more of an issue if/when more tools are added, so recommend reviewing the disk partitioning ASAP.

**Comment by pixie79** [comment]
The Partitioning follows best practice for security hardening and guidelines. The image is deliberately small to ensure it fits on lots of different devices. However, it is using lvm and the partitions can be extended as needed.
