### ISSUE TITLE
allow users to run openvpn

### ISSUE THREAD

**Issue by sohailkhawaja** [UKHomeOffice/development_environment#33]
I had to allow them manually but we need to fix them for future so they can use openvpn as standard normal linux users.

**Comment by pixie79** [comment]
They can, users are not allowed Sudo. If users use network manager they can add the VPN to the profile and connect no need for Sudo.

**Comment by osterzel** [comment]
Ideally this is then an issue for documenting if this has been raised. Since this is one of the core pieces of functionality to develop against an environment through a secure tunnel.

**Comment by pixie79** [comment]
Absolutely something needs to be added to the readme.

**Comment by pixie79** [comment]
Adding to FAQ.md in the base of the repo
