### ISSUE TITLE
New users should automatically be added to the docker group

### ISSUE THREAD

**Issue by Ian-T-Price** [UKHomeOffice/development_environment#34]
Docker cmds have to be run with sudo unless a user has been added to the docker group.

The install should add New users automatically to the docker group

**Comment by pixie79** [comment]
Sorry, This is not allowed by security requirements.

Allowing users to do a docker run would enable users to start docker containers in privileged mode on the machines and that in turn gives them access to root on the host system. As such docker may only be used against either external targets or minikube which is within a VM.

Sorry

Mark

**Comment by Ian-T-Price** [comment]
I'm not sure that I follow the logic of that.  Adding the user to the docker group just means they don't continually have keep using sudo to run docker commands.  With sudo access they can run in privileged mode anyway.

As we give users sudo access anyway they can add themselves to the docker group anyway.  This would just prevent all the "Cannot connect to the Docker daemon. Is the docker daemon running on this host?" error messages that are an annoying waste of time.

Without sudo or group access, they can't run docker commands so no point loading docker...

**Comment by pixie79** [comment]
The point is they are not allowed Sudo as they are not allowed root on the box.
