### ISSUE TITLE
Multiple Clamav issues

### ISSUE THREAD

**Issue by davidogbonnah** [UKHomeOffice/development_environment#43]
Clamav logs are constantly filling up the /tmp directory, and we are receiving several complaints from developers where the clamav daemon is using around 100% CPU causing build times to slow down.

**Comment by pixie79** [comment]
ClamAV will use a lot of CPU during builds this unfortunately can not be helped as we are required to do realtime scans of files and builds in their nature do a lot of file changes.

As for the tmp filling issue we have applied several fixes lately for that and it has not been noticed recently so please recreate the issue with the current code base. Then create a new ticket with full details and even better find the cause and PR.
