### ISSUE TITLE
Issues setting passwords

### ISSUE THREAD

**Issue by davidogbonnah** [UKHomeOffice/development_environment#44]
New users are experiencing difficulty with changing their passwords, which is required every thirty days. The new users password can only be changed via the the account created upon completing the desktop/laptop build. There is no restriction on the password set on the GUI, whereas the user will receive an error message stating their new password does not meet the requirements using the CLI.

**Comment by timgent** [comment]
Just a thought :)
https://www.wired.com/2016/03/want-safer-passwords-dont-change-often/

**Comment by pixie79** [comment]
Hm, not sure about 30 days I thought it was higher but this sounds like a gnome bug.

Users can always used the cli 'passwd' command to change thier own password and ideally we would encourage that.

Otherwise please feel free to research ensuring gnome password changing tool to use Pam controls.

**Comment by freddyp92** [comment]
We've had reports of users trying to change their password using both the GUI and the `passwd` command and neither worked.

**Comment by pixie79** [comment]
@freddyp92 there is a fix-passwd branch which has work started on the for this. It looks like there were two competing PAM modules running for changing passwords which would explain some of the weirdness but we do need to now ensure that GUI password changes are respecting the changes.

**Comment by freddyp92** [comment]
That probably explains the issues, thanks @pixie79
