### ISSUE TITLE
Access via SSH

### ISSUE THREAD

**Issue by davidogbonnah** [UKHomeOffice/development_environment#45]
We are unable to access other desktops or laptops or copy public keys remotely using public key authentication, restricting us from running ansible on remote machines. We require clarification on how we ought to connect to these machines remotely

**Comment by pixie79** [comment]
This is not a very clear issue, if you mean you can not ssh to servers using public keys then this is not true and works fine.

Likewise if you want to use ssh keys to connect to the laptops this should also work providing you have a valid user on the target device however, these scripts are not intended to be run remotely against a laptop.
