### ISSUE TITLE
Swap Space

### ISSUE THREAD

**Issue by davidogbonnah** [UKHomeOffice/development_environment#46]
We are currently having to remove and reinstate a smaller swap space file in order to increase the size of particular volumes. The image creates a swap space file which occupies the remainder of space on the hard drive after all volumes have been created

**Comment by pixie79** [comment]
This is the desired design, as the image is enabled to be put on variable size machines with limited disk space. As swap is of limited use it is the last in the provisioning pattern with the intention as machines are built the other disks can be resized as needed.

**Comment by sirv1ne** [comment]
This is still an issue as resizing a live in use partition after boot is cumbersome and can lead to data loss. A solution could be to have a small empty partition as the last one that's defined. This can then easily be resized to make way for extending or shrinking of other partitions without having to worry disabling or enabling swap on a machine.

**Comment by sirv1ne** [comment]
Fixed with latest merge
