### ISSUE TITLE
Default Keyboard

### ISSUE THREAD

**Issue by davidogbonnah** [UKHomeOffice/development_environment#47]
The default keyboard for all users is English (US) and requires changing to English (UK)

**Comment by pixie79** [comment]
This is an issue with gnome that it does not seem to respect the install option keyboard so currently users need to change the language themselves.
Generally though it is a user setting and would not be something we would want to be changing.

**Comment by freddyp92** [comment]
The US keyboard tends to give people problems with setting passwords and such. I don't believe it to be a major issue but it can cause inconveniences.
This can be fixed after provisioning by editing the /etc/default/keyboard file and changing XKBLAYOUT from "us" to "gb".

**Comment by pixie79** [comment]
Ah good @freddyp92 you know where the issue is. Please send a PR probably against the Generic install Role, to change it. I would suggest via the Lineinfile module.

**Comment by freddyp92** [comment]
Fixed: replace module used to change the default keyboard to English (UK) - in the Generic ansible role for both Debian and RedHat OS's
