### ISSUE TITLE
'Check sublime build' ansible task

### ISSUE THREAD

**Issue by freddyp92** [UKHomeOffice/development_environment#50]
TASK [sublime : Debian | check sublime build] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/subl --version", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
...ignoring

Not too sure what this does. I'm guessing it may not be mandatory as it was ignored after failing?

**Comment by SamFrier** [comment]
This task checks the version of sublime installed. If sublime is not installed, the task "fails" and subsequent tasks install sublime. In other words, the role should work fine as it is, it's just written in a slightly misleading way.
