### ISSUE TITLE
Default shell for new users is not /bin/bash

### ISSUE THREAD

**Issue by freddyp92** [UKHomeOffice/development_environment#51]
In the adduser.conf the default login shell is set as /usr/sbin/nologin instead of /bin/bash

This means that every new user created will not have the bash shell as default. This needs to be changed to /bin/bash before a new user is created.

**Comment by freddyp92** [comment]
This is also the same for the SHELL variable in the /etc/default/useradd file

**Comment by pixie79** [comment]
That would be the correct action - by default users should not have a login shell.

When creating users you should use the '-m' and set their shell. The default setting also cover system accounts which are not allowed login shells.
