### ISSUE TITLE
404 command not found when running curl command for additional DevOps tools

### ISSUE THREAD

**Issue by freddyp92** [UKHomeOffice/development_environment#52]
`bash: line 1: 404:: command not found`

When trying to run `curl https://raw.githubusercontent.com/UKHomeOffice/development_environment/develop/ansible/devops/install.sh | TAG=develop bash` to install the additional DevOps related tools.

**Comment by pixie79** [comment]
Guys please work with Sam, and use the Slack chat to discuss issues before creating them. Ideally it is much better to just submit the PR with a correction.

**Comment by SamFrier** [comment]
The instructions in the readme were outdated as our strategy regarding additional DevOps tools has changed and that URL no longer exists. If you want to install awesome-wm (currently the only extra DevOps tool) use this command:
`curl https://raw.githubusercontent.com/UKHomeOffice/development_environment/develop/ansible/install.sh | TAG=develop AWM=true bash` 
(this approach is subject to change if/when we decide to add more DevOps tools)

**Comment by freddyp92** [comment]
Thanks @SamFrier
