### ISSUE TITLE
ClamAV command task keeps failing

### ISSUE THREAD

**Issue by SignVOVA** [UKHomeOffice/development_environment#53]
TASK [clamav : command] ********************************************************
FAILED - RETRYING: TASK: clamav : command (10 retries left).
FAILED - RETRYING: TASK: clamav : command (9 retries left).
FAILED - RETRYING: TASK: clamav : command (8 retries left).
FAILED - RETRYING: TASK: clamav : command (7 retries left).
FAILED - RETRYING: TASK: clamav : command (6 retries left).
FAILED - RETRYING: TASK: clamav : command (5 retries left).
FAILED - RETRYING: TASK: clamav : command (4 retries left).
FAILED - RETRYING: TASK: clamav : command (3 retries left).
FAILED - RETRYING: TASK: clamav : command (2 retries left).
FAILED - RETRYING: TASK: clamav : command (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 10, "changed": true, "cmd": "/usr/local/bin/freshclam_status", "delta": "0:00:00.008354", "end": "2017-01-09 10:53:20.474530", "failed": true, "rc": 1, "start": "2017-01-09 10:53:20.466176", "stderr": "++ date '+%a %b %e'\n+ DATE='Mon Jan  9'\n++ cat /var/log/clamav/freshclam.log\n++ grep daily\n++ tail -n1000\n+ [[ '' =~ up to date ]]\n++ cat /var/log/clamav/freshclam.log\n++ grep daily\n++ tail -n1000\n+ [[ '' =~ updated ]]\n+ echo 'Error: Freshclam needs updating'\n+ exit 1", "stdout": "Error: Freshclam needs updating", "stdout_lines": ["Error: Freshclam needs updating"], "warnings": []}

**Comment by pixie79** [comment]
Hi,

Please leave proper bug reports - the above is not.

What Git tag were you running against?
Did you have an internet connection?

Lots of things can affect good running of the command - the failure in itself is valid.

**Comment by SignVOVA** [comment]
I ran the curl command `curl https://raw.githubusercontent.com/UKHomeOffice/development_environment/develop/ansible/install.sh | TAG=develop bash` 
So it was the develop tag, and yes I do have an internet connection.

I ran the command again and it has given the same error, as posted above.
