### ISSUE TITLE
Chromium on Dev laptops

### ISSUE THREAD

**Issue by mpbristol** [UKHomeOffice/development_environment#58]
Chromium on the Dev laptops would be a useful addition.

**Comment by Ian-T-Price** [comment]
Do you mean Chrome?  Why propose Chromium?

The current plans are to install user space software separately from the standard build using separate ansible roles.

**Comment by mpbristol** [comment]
Dev laptops are Ubuntu, for which Chromium is the only option without using a windows VM.

**Comment by sublimino** [comment]
This suggests Chrome is available for Ubuntu https://www.google.co.uk/chrome/browser/desktop/

(I run it happily on Debian testing)

**Comment by SamFrier** [comment]
Added a role to install standard Chrome, seems to be working fine from what I can tell. If users need to install a specific version for whatever reason they can do that in user space.
