### ISSUE TITLE
Slack Target Package configured multiple times & permissions

### ISSUE THREAD

**Issue by Ian-T-Price** [UKHomeOffice/development_environment#69]
## ITP will apply the fix for this issue
=================

1) The user interface is showing a 'No entry' sign This is for update errors

2) End user receives errors due to 600 or 640 permissions set on files in /etc/apt/sources.list.d 

## Expected Behaviour
No errors should be shown when running **apt-get update**

## Current Behaviour
running **apt-get update** on the CLI gives:
 
**W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/packagecloud_io_slacktechnologies_slack_debian.list:1 and /etc/apt/sources.list.d/slack.list:3**

## Possible Solution
1) Remove either 
/etc/apt/sources.list.d/packagecloud_io_slacktechnologies_slack_debian.list
OR
/etc/apt/sources.list.d/slack.list

2) change permissions to 644 for all files in /etc/apt/sources.list.d

## Steps to Reproduce (for bugs)

1. Run **apt-get update**

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Ian-T-Price** [comment]
Actually I think the permissions problem was down to me playing with other things... ;-)
Will double check before applying changes

**Comment by pixie79** [comment]
confirmed multiple versions removed but permissions are incorrect will fix up

**Comment by Ian-T-Price** [comment]
Thanks Mark.  I was going to get a Round Tuit.  Probably when I next go down to Cornwall; they sell them down there ;-)
