### ISSUE TITLE
Review needed for awesome-wm role

### ISSUE THREAD

**Issue by SamFrier** [UKHomeOffice/development_environment#75]
awesome-wm role is currently forked from a public GitHub, but as it is available as an Ubuntu package it would probably be safer to write our own role using this approach. (I'm not sure if this is also true for CentOS but since it will only be used by DevOps who use Ubuntu machines this is probably not an issue.)

**Comment by pixie79** [comment]
This role should be changed to use the main awesome-wm ubuntu package

**Comment by SamFrier** [comment]
I've created an alternative role that uses the Ubuntu package: https://github.com/SamFrier/ansible-role-awesome

If this is OK I can transfer it over to UKHomeOffice

**Comment by pixie79** [comment]
role removed and using a package instead
