### ISSUE TITLE
User is prompted for admin password when connecting to VPN

### ISSUE THREAD

**Issue by robhowlett** [UKHomeOffice/development_environment#98]
## Expected Behaviour
When setting up a new VPN connection, the user should not be prompted for any password

## Current Behaviour
When setting up a new VPN connection, the user is prompted for the admin user's password

## Steps to Reproduce (for bugs)
1. Download VPN connection file
2. Create new VPN connection from GUI using the option to configure from a file

## Context
Non-admin user must know the admin user's password to connect to VPN

## Your Environment
Clean build using this repo

**Comment by jamesdowdall** [comment]
We have encountered the same issue, this is because by default the GUI tries to apply the vpn config to all users. You need to deselect this under the general tab when configuring the VPN (to only apply to the current user) - this does not require escalated privileges.
